### ISSUE TITLE
switch cannot connect to computer

### ISSUE THREAD

**Issue by yawhide** [reswitched/PegaSwitch#1]
Hello,

Here is the exception:
```
D, [2017-03-13T22:04:36.482691 #7940] DEBUG -- : <> Receiving incoming query (43 bytes) to RubyDNS::UDPHandler...
D, [2017-03-13T22:04:36.483187 #7940] DEBUG -- : <47316> Processing question conntest.nintendowifi.net Resolv::DNS::Resource::IN::A...
D, [2017-03-13T22:04:36.483187 #7940] DEBUG -- : <47316> Searching for conntest.nintendowifi.net Resolv::DNS::Resource::IN::A
D, [2017-03-13T22:04:36.483187 #7940] DEBUG -- : <47316> Checking rule [/./, Resolv::DNS::Resource::IN::A]...
D, [2017-03-13T22:04:36.483187 #7940] DEBUG -- : <47316> Regexp pattern matched with #<MatchData "c">.
I, [2017-03-13T22:04:36.483187 #7940]  INFO -- : Resource class: Resolv::DNS::Resource::IN::A
E, [2017-03-13T22:04:36.483187 #7940] ERROR -- : <47316> Exception thrown while processing conntest.nintendowifi.net Resolv::DNS::Resource::IN::A!
E, [2017-03-13T22:04:36.483187 #7940] ERROR -- : ArgumentError: cannot interpret as IPv4 address: nil
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:2346:in `create'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/2.3.0/resolv.rb:2147:in `initialize'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/transaction.rb:130:in `new'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/transaction.rb:130:in `respond!'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : rdns.rb:17:in `block (2 levels) in <main>'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:217:in `call'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:327:in `block (2 levels) in process'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:325:in `catch'
E, [2017-03-13T22:04:36.483687 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:325:in `block in process'
E, [2017-03-13T22:04:36.484187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:322:in `each'
E, [2017-03-13T22:04:36.484187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:322:in `process'
E, [2017-03-13T22:04:36.484187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/transaction.rb:192:in `process'
E, [2017-03-13T22:04:36.484187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:106:in `block in process_query'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:98:in `each'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/server.rb:98:in `process_query'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/handler.rb:55:in `process_query'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubydns-1.0.3/lib/rubydns/handler.rb:87:in `respond'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
E, [2017-03-13T22:04:36.484688 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
E, [2017-03-13T22:04:36.485187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
E, [2017-03-13T22:04:36.485187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
E, [2017-03-13T22:04:36.485187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
E, [2017-03-13T22:04:36.485187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
E, [2017-03-13T22:04:36.485187 #7940] ERROR -- : C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
D, [2017-03-13T22:04:36.485187 #7940] DEBUG -- : <47316> Time to process request: 0.002s
D, [2017-03-13T22:04:36.485187 #7940] DEBUG -- : <47316> Writing 43 bytes response to client via UDP...
```

I tried the following options:

### fails at connecting to router (in the animation)
ip address settings - **automatic**
dns settings - **manual**
- primary dns **192.168.x.x** (my computer's local ip)
- secondary dns (same as primary)

proxy settings - **off**

### fails at connecting to the internet (animation)
ip address settings - **automatic**
dns settings - **manual**
- primary dns - **192.168.x.x** (my computer's local ip)
- secondary dns (same as primary)

proxy settings - **on**
- server **192.168.x.x** (same as primary dns)
- port **8081**
- auto-authentication - **off**

any ideas how to make this work?

os: windows 10
ruby version - 2.3.3p222
nodejs 7.5.0
python 2.7.13

**Comment by daeken** [comment]
Did you open the requisite ports on your firewall?  It's possible that it's just failing silently due to that.  To test (not recommended for more than just that, mind you), I suggest you disable the Windows firewall and try again.

**Comment by yawhide** [comment]
i manually opened the ports following this guide:

http://www.thewindowsclub.com/block-open-port-windows-8-firewall

udp 53, tcp 8081/80

**Comment by yawhide** [comment]
ok so I changed the proxy settings to use port 80 and now I see the giant "reload" button. i am confused what to do next. tried tapping the button, nothing seems to happen. I dont see any logs from the `node debug.js` nor the `npm start` windows.

**Comment by daeken** [comment]
If you're seeing that, you should also see 'Started' pop up in the Python console (for serve.py), then hopefully 'Switch connected' in the `node debug.js` window.  Are you seeing anything in the Python console?

**Comment by yawhide** [comment]
no nothing in the python console nor the `node debug`. what are the switch settings that you are using?

**Comment by Andoryuuta** [comment]
"ArgumentError: cannot interpret as IPv4 address: nil" is because rdns.rb expects your public IP to be passed in as a command line arg [see here](https://github.com/reswitched/PegaSwitch/blob/master/rdns.rb#L13)

Also, port 8100 needs to be opened for websocket [see here](https://github.com/reswitched/PegaSwitch/blob/master/debug.js#L12)

**Comment by yawhide** [comment]
thanks @Andoryuuta just had to pass my computer's local ip to the rdns.rb.

**Comment by SomeoneWeird** [comment]
@yawhide sorry, I'll push a fix to the readme to make that more obvious
