### ISSUE TITLE
"node debug.js" returns errors

### ISSUE THREAD

**Issue by jaisongreen** [reswitched/PegaSwitch#8]
```
node debug.js
/Users/jaisongreen/Projects/PegaSwitch/debug.js:30
let connection
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

running node using "use_strict" produces more errors.

```
node --use_strict debug.js
/Users/jaisongreen/Projects/PegaSwitch/debug.js:42
function sendMsg (cmd, args = []) {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by jaisongreen** [comment]
Nevermind, I needed to update my Node version.
